baseURL = "/my/"
languageCode = "zh-CN"
title = "sunnymix.com"
theme = "draft"
favicon = "favicon.png"
publishDir = "public/my/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params]
  sitename = ""
  copyright = "© 2013-2021 sunnymix.com"
  certificate = " 赣ICP备20006923号"
  dateform = "2006.01.02"
  enableInlineShortcodes = true
  pygmentsCodeFences = true
  pygmentsUseClasses = true
  highlight = true
