baseURL = "/"
languageCode = "zh-CN"
title = "sunnymix.com"
theme = "booklet"

[menu]
  [[menu.primary]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.primary]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3

  [[menu.primary]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 4

[params]
  faviconfile = "favicon.png"
  enableInlineShortcodes = true
  pygmentsCodeFences = true
  pygmentsUseClasses = true
  copyright = "© 2013－2021 sunnymix.com, all rights reserved"
  certificate = "赣ICP备20006923号"
  highlight = true
  sitename = "Sunny Mix"
