baseURL = "/"
languageCode = "zh-CN"
title = "sunnymix.com"
theme = "minima"
favicon = "favicon.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  sitename = ""
  copyright = "© 2013－2021 sunnymix.com, all rights reserved"
  certificate = "（赣ICP备20006923号）"
  enableInlineShortcodes = true
  pygmentsCodeFences = true
  pygmentsUseClasses = true
  highlight = true
